"""Rebuild every table in results/tables.md from raw/ (stdlib only, ~2 minutes)."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import stats as S, extra as E
HERE = Path(__file__).resolve().parent
layers = S.HARD
md = ["# Tables (generated by run.py)", "", f"Layers: {', '.join(layers)}. Models: see README.", ""]
md += E.section_audit(layers) + [""] + E.section_plurality(layers) + [""] + E.section_quoted(layers) + [""] + S.section_matrix(layers) + [""] + S.section_matrix_deep(layers) + [""] + S.section_copula(layers) + [""]
md += S.section_samples(layers) + [""] + S.section_samples_deep(layers) + [""] + S.section_betabin(layers) + [""]
md += S.section_debate(layers) + S.section_debate_deep(layers) + [""] + S.section_debate_offline(layers) + [""] + S.section_homodebate(layers) + [""]
md += S.section_aggregate(layers) + [""] + S.section_judge(layers) + [""] + S.section_judge_deep(layers) + [""] + S.section_endorse(layers) + [""]
md += S.section_personas(layers) + [""] + S.section_budget(layers) + [""] + S.section_tokens(layers) + [""] + E.section_cost(layers) + [""] + E.section_ties(layers)
# Legacy policy: truncated answers counted as wrong (what v1 and v2 of the note did, by accident). Same sections, for comparison.
S.TRUNC_AS_WRONG = True
md += ["", "# L. Legacy tables: truncated answers counted as wrong", "", "The tables above treat a truncated answer (completion cap hit before a final line) as missing. The first two versions of the note counted such rows as wrong in the debate and judge stages, which is what these tables reproduce; they are kept so that the two policies can be compared row by row.", ""]
md += [l.replace("## ", "## L-", 1) if l.startswith("## ") else l for l in S.section_debate(layers) + S.section_debate_deep(layers) + [""] + S.section_debate_offline(layers) + [""] + S.section_homodebate(layers) + [""] + S.section_judge(layers) + [""] + S.section_judge_deep(layers)]
S.TRUNC_AS_WRONG = False
(HERE / "results").mkdir(exist_ok=True)
(HERE / "results" / "tables.md").write_text("\n".join(md) + "\n")
print("\n".join(md))
